import type { Employee } from "@/types/employee";

export const mockEmployees: Employee[] = [
  {
    id: "EMP001",
    name: "Somchai Prasert",
    name_th: "สมชาย ประเสริฐ",
    position: "Managing Director",
    phone: "+66 89 123 4567",
    employment_status: "active",
    birthdate: "1975-03-15",
    start_date: "2010-01-15",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "Management", email: "somchai.p@pta.co.th", is_primary: 1 },
      { company: "PT4", department: "Management", email: "somchai.p@pt4.co.th", is_primary: 0 },
    ],
  },
  {
    id: "EMP002",
    name: "Nattaporn Chaiwat",
    name_th: "ณัฐพร ชัยวัฒน์",
    position: "Manager",
    phone: "+66 81 234 5678",
    employment_status: "active",
    start_date: "2015-06-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "HR and GA", email: "nattaporn.c@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP003",
    name: "Wipada Srisawat",
    name_th: "วิภาดา ศรีสวัสดิ์",
    position: "Senior Officer",
    phone: "+66 92 345 6789",
    employment_status: "active",
    start_date: "2018-03-15",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "Accounting", email: "wipada.s@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP004",
    name: "Kittipong Suwan",
    name_th: "กิตติพงษ์ สุวรรณ",
    position: "Senior Programmer",
    phone: "+66 83 456 7890",
    employment_status: "active",
    start_date: "2019-08-01",
    created_at: "2024-01-15",
    updated_at: "2024-01-20",
    assignments: [
      { company: "PTA", department: "IT", email: "kittipong.s@pta.co.th", is_primary: 1 },
      { company: "PT4", department: "IT", email: "kittipong.s@pt4.co.th", is_primary: 0 },
      { company: "PTE", department: "IT", email: "kittipong.s@pte.co.th", is_primary: 0 },
    ],
  },
  {
    id: "EMP005",
    name: "Arisa Tanaka",
    name_th: "อริสา ทานากะ",
    position: "Engineer(Lv3)",
    phone: "+66 94 567 8901",
    employment_status: "active",
    start_date: "2020-02-01",
    birthdate: "1992-01-29",
    created_at: "2024-01-01",
    assignments: [
      { company: "PT4", department: "Production Engineer", email: "arisa.t@pt4.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP006",
    name: "Piyapong Rattana",
    name_th: "ปิยะพงษ์ รัตนะ",
    position: "Senior Supervisor",
    phone: "+66 85 678 9012",
    employment_status: "active",
    start_date: "2016-11-15",
    created_at: "2024-01-01",
    assignments: [
      { company: "PT4", department: "Production", email: "piyapong.r@pt4.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP007",
    name: "Siriporn Maneerat",
    name_th: "ศิริพร มณีรัตน์",
    position: "Officer",
    phone: "+66 86 789 0123",
    employment_status: "active",
    start_date: "2021-04-01",
    created_at: "2024-01-20",
    assignments: [
      { company: "PTE", department: "Quality Management", email: "siriporn.m@pte.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP008",
    name: "Thanawat Chaidee",
    name_th: "ธนวัฒน์ ใจดี",
    position: "Senior Technician",
    phone: "+66 87 890 1234",
    employment_status: "active",
    start_date: "2017-07-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "Maintenance", email: "thanawat.c@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP009",
    name: "Pattaraporn Boonma",
    name_th: "ภัทราภรณ์ บุญมา",
    position: "Staff",
    phone: "+66 88 901 2345",
    employment_status: "active",
    start_date: "2022-01-15",
    created_at: "2024-01-01",
    assignments: [
      { company: "PT4", department: "Logistics", email: "pattaraporn.b@pt4.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP010",
    name: "Worawut Phongsak",
    name_th: "วรวุฒิ พงศ์ศักดิ์",
    position: "Supervisor (Lv2)",
    phone: "+66 89 012 3456",
    employment_status: "active",
    start_date: "2018-09-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTE", department: "Safety & Environment", email: "worawut.p@pte.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP011",
    name: "Chonlada Wongsa",
    name_th: "ชลลดา วงศา",
    position: "Manager",
    phone: "+66 90 123 4567",
    employment_status: "active",
    start_date: "2014-05-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PT4", department: "Accounting", email: "chonlada.w@pt4.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP012",
    name: "Prawit Sangthong",
    name_th: "ประวิทย์ แสงทอง",
    position: "Manager",
    phone: "+66 91 234 5678",
    employment_status: "active",
    start_date: "2013-08-15",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "Production", email: "prawit.s@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP013",
    name: "Sumalee Inthachai",
    name_th: "สุมาลี อินทไชย",
    position: "Senior Officer",
    phone: "+66 82 345 6789",
    employment_status: "inactive",
    start_date: "2019-02-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTA", department: "HR and GA", email: "sumalee.i@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP014",
    name: "Natthawut Jitprasert",
    name_th: "ณัฐวุฒิ จิตประเสริฐ",
    position: "Programmer",
    phone: "+66 93 456 7890",
    employment_status: "active",
    start_date: "2023-06-01",
    created_at: "2024-01-25",
    assignments: [
      { company: "PTA", department: "IT", email: "natthawut.j@pta.co.th", is_primary: 1 },
    ],
  },
  {
    id: "EMP015",
    name: "Kanokwan Phetdum",
    name_th: "กนกวรรณ เพชรดำ",
    position: "Officer",
    phone: "+66 84 567 8901",
    employment_status: "active",
    start_date: "2021-11-01",
    created_at: "2024-01-01",
    assignments: [
      { company: "PTE", department: "Logistics", email: "kanokwan.p@pte.co.th", is_primary: 1 },
    ],
  },
];
